//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEvaluate")]
public interface IEvaluate
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEvaluate/Evaluate", ReplyAction="http://tempuri.org/IEvaluate/EvaluateResponse")]
    double[] Evaluate(double Kcn, double KsoilW, double KsoilK, double Kcanmax, double Kpovrs, double Kpodz, double Krecnamreza, double KTs_r, double KPlaps, double KTlaps, double KBmelt);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IEvaluateChannel : IEvaluate, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class EvaluateClient : System.ServiceModel.ClientBase<IEvaluate>, IEvaluate
{
    
    public EvaluateClient()
    {
    }
    
    public EvaluateClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EvaluateClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvaluateClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EvaluateClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public double[] Evaluate(double Kcn, double KsoilW, double KsoilK, double Kcanmax, double Kpovrs, double Kpodz, double Krecnamreza, double KTs_r, double KPlaps, double KTlaps, double KBmelt)
    {
        return base.Channel.Evaluate(Kcn, KsoilW, KsoilK, Kcanmax, Kpovrs, Kpodz, Krecnamreza, KTs_r, KPlaps, KTlaps, KBmelt);
    }
}
