//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5446
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFManagerLibrary
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "JobParameters", Namespace = "http://schemas.datacontract.org/2004/07/WCFManagerLibrary")]
    public partial class JobParameters : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private double[] ParametersField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "job_status", Namespace = "http://schemas.datacontract.org/2004/07/WCFManagerLibrary")]
    public enum job_status : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WAITING = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WORKING = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DONE = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "JobResult", Namespace = "http://schemas.datacontract.org/2004/07/WCFManagerLibrary")]
    public partial class JobResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string MessageField;

        private double[] ResultField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "JobIDandResult", Namespace = "http://schemas.datacontract.org/2004/07/WCFManagerLibrary")]
    public partial class JobIDandResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string JobIDField;

        private string MessageField;

        private double[] ResultField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobID
        {
            get
            {
                return this.JobIDField;
            }
            set
            {
                this.JobIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Result
        {
            get
            {
                return this.ResultField;
            }
            set
            {
                this.ResultField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "JobIDandParameters", Namespace = "http://schemas.datacontract.org/2004/07/WCFManagerLibrary")]
    public partial class JobIDandParameters : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string JobIDField;

        private WCFManagerLibrary.JobParameters JobParametersField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string JobID
        {
            get
            {
                return this.JobIDField;
            }
            set
            {
                this.JobIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCFManagerLibrary.JobParameters JobParameters
        {
            get
            {
                return this.JobParametersField;
            }
            set
            {
                this.JobParametersField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IWCFManager")]
public interface IWCFManager
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/doJob_UI", ReplyAction = "http://tempuri.org/IWCFManager/doJob_UIResponse")]
    string doJob_UI(WCFManagerLibrary.JobParameters jobParameters);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/getStatus_UI", ReplyAction = "http://tempuri.org/IWCFManager/getStatus_UIResponse")]
    WCFManagerLibrary.job_status getStatus_UI(string jobID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/getResult_UI", ReplyAction = "http://tempuri.org/IWCFManager/getResult_UIResponse")]
    WCFManagerLibrary.JobResult getResult_UI(string jobID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/getResultPackage_UI", ReplyAction = "http://tempuri.org/IWCFManager/getResultPackage_UIResponse")]
    WCFManagerLibrary.JobIDandResult[] getResultPackage_UI(string[] jobs);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/getJob_WN", ReplyAction = "http://tempuri.org/IWCFManager/getJob_WNResponse")]
    WCFManagerLibrary.JobIDandParameters getJob_WN(string ID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/JobDone_WN", ReplyAction = "http://tempuri.org/IWCFManager/JobDone_WNResponse")]
    void JobDone_WN(WCFManagerLibrary.JobResult result, string jobID);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IWCFManager/waitDone_package_UI", ReplyAction = "http://tempuri.org/IWCFManager/waitDone_package_UIResponse")]
    void waitDone_package_UI(string[] jobsToWait);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IWCFManagerChannel : IWCFManager, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class WCFManagerClient : System.ServiceModel.ClientBase<IWCFManager>, IWCFManager
{

    public WCFManagerClient()
    {
    }

    public WCFManagerClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public WCFManagerClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WCFManagerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public WCFManagerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public string doJob_UI(WCFManagerLibrary.JobParameters jobParameters)
    {
        return base.Channel.doJob_UI(jobParameters);
    }

    public WCFManagerLibrary.job_status getStatus_UI(string jobID)
    {
        return base.Channel.getStatus_UI(jobID);
    }

    public WCFManagerLibrary.JobResult getResult_UI(string jobID)
    {
        return base.Channel.getResult_UI(jobID);
    }

    public WCFManagerLibrary.JobIDandResult[] getResultPackage_UI(string[] jobs)
    {
        return base.Channel.getResultPackage_UI(jobs);
    }

    public WCFManagerLibrary.JobIDandParameters getJob_WN(string ID)
    {
        return base.Channel.getJob_WN(ID);
    }

    public void JobDone_WN(WCFManagerLibrary.JobResult result, string jobID)
    {
        base.Channel.JobDone_WN(result, jobID);
    }

    public void waitDone_package_UI(string[] jobsToWait)
    {
        base.Channel.waitDone_package_UI(jobsToWait);
    }
}
